global:
  smtp_smarthost: '$smtp.office365.com:587'
  smtp_from: 'khenshin_dumer@hotmail.com'
  smtp_auth_username: 'khenshin_dumer@hotmail.com'
  smtp_auth_password: 'Jinchuriki1!'
  smtp_require_tls: true

route:
  receiver: email-me

receivers:
  - name: email-me
    email_configs:
      - to: 'irene_romero_95@hotmail.com'
